# Generated by Django 6.0.2 on 2026-02-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AddField(
            model_name='news',
            name='region',
            field=models.CharField(blank=True, choices=[('toshkent', 'Toshkent'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('navoiy', 'Navoiy'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('xorazm', 'Xorazm'), ('qoraqalpogiston', "Qoraqalpog'iston")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
